// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikjwrzaeaaceirytwsos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrandyemFlYWFjZWlyeXR3c29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTAwMjUsImV4cCI6MjA3MTk2NjAyNX0.3SkyzBpX0XMXM0gYrljYF1WX1eg8gYNl0FlC17EvGF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});